# Generated by Django 4.1.4 on 2022-12-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image_blog', models.ImageField(blank=True, upload_to='image_blogs')),
                ('content_blog', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('tags', models.CharField(choices=[('python', 'Python'), ('SEO', 'SEO'), ('WEB DEVELOPMENT', 'WEB DEVELOPMENT'), ('python SEO', 'PYTHON SEO'), ('knowledge python', 'Knowledge Python'), ('web scraping', 'Web Scraping'), ('python scraping', 'Python Scraping'), ('python crawl', 'Python Crawl'), ('programing', 'Programing'), ('other', 'Other')], max_length=200)),
            ],
        ),
    ]
