# Generated by Django 4.1.4 on 2022-12-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSEO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_encode',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
