# Generated by Django 4.1.4 on 2022-12-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogSEO', '0002_blog_title_encode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title_encode',
        ),
    ]
